server {
    listen 80;
    root /var/www/html;
    index index.php index.html;

    location = /info.php {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/info.php;
    }

    location /laravel/ {
        alias /var/www/html/laravel/public/;
        index index.php;
        try_files $uri $uri/ @laravel;
    }
    location @laravel {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/laravel/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }
    location ~ ^/laravel/(.+\.php)$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/laravel/public/$1;
        fastcgi_param REQUEST_URI $request_uri;
    }

    location /drupal/ {
        alias /var/www/html/drupal/web/;
        index index.php;
        try_files $uri $uri/ @drupal;
    }
    location @drupal {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/drupal/web/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }
    location ~ ^/drupal/(.+\.php)$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/drupal/web/$1;
        fastcgi_param REQUEST_URI $request_uri;
    }
}
